### ISSUE TITLE
Cannot use finetuned model from huggingface

### ISSUE THREAD

**Issue by J-Korn** [ufal/whisper_streaming#108]
I am trying to use https://huggingface.co/Sandiago21/whisper-large-v2-greek
by passing 'Sandiago21/whisper-large-v2-greek' to the model argument
and I'm getting the following error:

 ```
Loading Whisper Sandiago21/whisper-large-v2-greek model for el...
 whisper-server-DEBUG: Starting new HTTPS connection (1): huggingface.co:443
 whisper-server-DEBUG: https://huggingface.co:443 "GET /api/models/Sandiago21/whisper-large-v2-greek/revision/main HTTP/1.1" 200 4724
Exception in thread Thread-3 (run_whisper_server):
 Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
     self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
     self._target(*self._args, **self._kwargs)
  File "/var/www/html/whisper-streaming/whisper_realtime.py", line 549, in run_whisper_server
     online, min_chunk = load_whisper_model(lan,siz)
  File "/var/www/html/whisper-streaming/whisper_realtime.py", line 98, in load_whisper_model
     asr = asr_cls(modelsize=size, lan=language, cache_dir=args.model_cache_dir, model_dir=args.model_dir)
  File "/var/www/html/whisper-streaming/whisper_online.py", line 39, in __init__
     self.model = self.load_model(modelsize, cache_dir, model_dir)
  File "/var/www/html/whisper-streaming/whisper_online.py", line 113, in load_model
     model = WhisperModel(model_size_or_path, device="cuda", compute_type="float16", download_root=cache_dir)
  File "/usr/local/lib/python3.10/dist-packages/faster_whisper/transcribe.py", line 145, in __init__
    self.model = ctranslate2.models.Whisper(
RuntimeError: Unable to open file 'model.bin' in model '/root/.cache/huggingface/hub/models--Sandiago21--whisper-large-v2-greek/snapshots/a193714557f38a3e6c36a2c6526a5c25b39ae937'
```

In that dir I have 
```
# ls /root/.cache/huggingface/hub/models--Sandiago21--whisper-large-v2-greek/snapshots/a193714557f38a3e6c36a2c6526a5c25b39ae937/
added_tokens.json  config.json  generation_config.json  merges.txt  normalizer.json  preprocessor_config.json  pytorch_model.bin  README.md  runs  special_tokens_map.json  tokenizer_config.json  training_args.bin  vocab.json
```

Simply renaming the pytorch_model.bin ->model.bin gives the following

```
Traceback (most recent call last):
|   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
     self.run()
   File "/usr/lib/python3.10/threading.py", line 953, in run
     self._target(*self._args, **self._kwargs)
   File "/var/www/html/whisper-streaming/whisper_realtime.py", line 549, in run_whisper_server
    online, min_chunk = load_whisper_model(lan,siz)
   File "/var/www/html/whisper-streaming/whisper_realtime.py", line 98, in load_whisper_model
     asr = asr_cls(modelsize=size, lan=language, cache_dir=args.model_cache_dir, model_dir=args.model_dir)
  File "/var/www/html/whisper-streaming/whisper_online.py", line 39, in __init__
     self.model = self.load_model(modelsize, cache_dir, model_dir)
   File "/var/www/html/whisper-streaming/whisper_online.py", line 113, in load_model
    model = WhisperModel(model_size_or_path, device="cuda", compute_type="float16", download_root=cache_dir)
   File "/usr/local/lib/python3.10/dist-packages/faster_whisper/transcribe.py", line 145, in __init__
     self.model = ctranslate2.models.Whisper(
 RuntimeError: Unsupported model binary version. This executable supports models with binary version v6 or below, but the model has binary version v67324752. This usually means that the model was generated by a later version of CTranslate2. (Forward compatibility is not guaranteed.)
```

**Comment by Gldkslfmsd** [comment]
hi, which model argument exactly do you use? read documentation, check whether it's correct

**Comment by J-Korn** [comment]
I'm using
`asr_cls(modelsize=size, lan=language, cache_dir=args.model_cache_dir, model_dir=args.model_dir)`
with
`asr_cls = FasterWhisperASR`
and
`size = "Sandiago21/whisper-large-v2-greek"`

According to FasterWhisper documentation, loading a model directly from huggingface should work with this syntax, for example
`model = faster_whisper.WhisperModel("username/whisper-large-v3-ct2")`

**Comment by Gldkslfmsd** [comment]
Maybe this model is not in the format for faster_whisper and must be converted first.
Try the model with offline faster_whisper first, if it doesn't work, make it working by their instructions.

**Comment by J-Korn** [comment]
It had to be converted with
ct2-transformers-converter --model "Sandiago21/whisper-large-v2-greek" --output_dir whisper-large-v2-ct2
--copy_files tokenizer.json preprocessor_config.json --quantization float16

Then I can use "whisper-large-v2-ct2" as model size.

Thank you for your help
