### ISSUE TITLE
Issue with VAC

### ISSUE THREAD

**Issue by bchinnari** [ufal/whisper_streaming#142]
Hi ,  I am trying to use VAD with whisper streaming . I am getting following error

```
(faster_whisper) ➜  whisper_streaming git:(main) ✗ python whisper_online.py ~/EG.wav  --model small --language en  --vac
INFO	Audio duration is: 6.00 seconds
INFO	Loading Whisper small model for en...
INFO	done. It took 2.52 seconds.
Using cache found in /Users/bhargav/.cache/torch/hub/snakers4_silero-vad_master
Traceback (most recent call last):
  File "/Users/bhargav/open_WORK/whisper_streaming/whisper_online.py", line 842, in <module>
    online.insert_audio_chunk(a)
  File "/Users/bhargav/open_WORK/whisper_streaming/whisper_online.py", line 572, in insert_audio_chunk
    res = self.vac(audio)
  File "/Users/bhargav/open_WORK/whisper_streaming/silero_vad1.py", line 113, in __call__
    ret = super().__call__(self.buffer, return_seconds=return_seconds)
  File "/Users/bhargav/open_WORK/whisper_streaming/silero_vad1.py", line 74, in __call__
    speech_prob = self.model(x, self.sampling_rate).item()
  File "/Users/bhargav/miniconda3/envs/faster_whisper/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/bhargav/miniconda3/envs/faster_whisper/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
torch.jit.Error: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/vad/model/vad_annotator.py", line 26, in forward
    if _2:
      _3 = torch.format(_0, (torch.size(x0))[-1])
      ops.prim.RaiseException(_3, "builtins.ValueError")
      ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    else:
      pass

Traceback of TorchScript, original code (most recent call last):
  File "/home/keras/notebook/nvme1/adamnsandle/silero-models-research/vad/model/vad_annotator.py", line 480, in forward
        num_samples = 512 if sr == 16000 else 256
        if x.shape[-1] != num_samples:
            raise ValueError(f"Provided number of samples is {x.shape[-1]} (Supported values: 256 for 8000 sample rate, 512 for 16000)")
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    
        batch_size = x.shape[0]
builtins.ValueError: Provided number of samples is 720 (Supported values: 256 for 8000 sample rate, 512 for 16000)
```

How to fix this error

**Comment by bchinnari** [comment]
Posted this question in silero_vad repo.
