### ISSUE TITLE
Using `large-v3-turbo` with `faster-whisper` gives "Invalid model size" error in `whisper_online_server.py`

### ISSUE THREAD

**Issue by essovius** [ufal/whisper_streaming#143]
```shell
python whisper_online_server.py --host localhost --port 43001 --model large-v3-turbo --task transcribe --vac --vad --buffer_trimming segment --lan tr --warmup-file sinan.wav
INFO    Loading Whisper large-v3-turbo model for tr...
Traceback (most recent call last):
  File "H:\wisp\whisper_online_server.py", line 31, in <module>
    asr, online = asr_factory(args)
                  ^^^^^^^^^^^^^^^^^
  File "H:\wisp\whisper_online.py", line 682, in asr_factory
    asr = asr_cls(modelsize=size, lan=args.lan, cache_dir=args.model_cache_dir, model_dir=args.model_dir)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\wisp\whisper_online.py", line 43, in __init__
    self.model = self.load_model(modelsize, cache_dir, model_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\wisp\whisper_online.py", line 119, in load_model
    model = WhisperModel(model_size_or_path, device="cuda", compute_type="float16", download_root=cache_dir)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\faster_whisper\transcribe.py", line 139, in __init__
    model_path = download_model(
                 ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\faster_whisper\utils.py", line 78, in download_model
    raise ValueError(
ValueError: Invalid model size 'large-v3-turbo', expected one of: tiny.en, tiny, base.en, base, small.en, small, medium.en, medium, large-v1, large-v2, large-v3, large, distil-large-v2, distil-medium.en, distil-small.en, distil-large-v3
```

**Comment by Gldkslfmsd** [comment]
I think you need to reinstall faster-whisper to the version that knows about large-v3-turbo. 
Or download the model and use the --model_dir option.

**Comment by Gldkslfmsd** [comment]
reopen if you need
