### ISSUE TITLE
Custom model names not allowed

### ISSUE THREAD

**Issue by flatsiedatsie** [ufal/whisper_streaming#65]
I'm trying to run Whisper Streaming with a different model: `ggml-base-q5_1.bin`, which I believe is a quantified version of the normal base model. But it won't let me:

```
whisper_online.py: error: argument --model: invalid choice: 'ggml-base-q5_1.bin' (choose from 'tiny.en', 'tiny', 'base.en', 'base', 'small.en', 'small', 'medium.en', 'medium', 'large-v1', 'large-v2', 'large-v3', 'large')
```

I was hoping that using the `--offline` flag would allow me to fully override the model name, but alas. Switching from `model-cache-dir` to `model-dir` also had no effect.

Would it be an idea to allow custom model names? Perhaps the code could check if the file exists before doing the filename check?

**Comment by flatsiedatsie** [comment]
I see that FasterWhisper then complains.

```
Loading Whisper ggml-base-q5_1.bin model for en... Traceback (most recent call last):
  File "/home/pi/.webthings/whisper_streaming/whisper_online_server.py", line 41, in <module>
    asr = asr_cls(modelsize=size, lan=language, cache_dir=args.model_cache_dir, model_dir=args.model_dir)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.webthings/whisper_streaming/whisper_online.py", line 41, in __init__
    self.model = self.load_model(modelsize, cache_dir, model_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.webthings/whisper_streaming/whisper_online.py", line 123, in load_model
    model = WhisperModel(modelsize, device="cpu", compute_type="int8") #, download_root="faster-disk-cache-dir/")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/faster_whisper/transcribe.py", line 127, in __init__
    model_path = download_model(
                 ^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/faster_whisper/utils.py", line 76, in download_model
    raise ValueError(
ValueError: Invalid model size 'ggml-base-q5_1.bin', expected one of: tiny.en, tiny, base.en, base, small.en, small, medium.en, medium, large-v1, large-v2, large-v3, large, distil-large-v2, distil-medium.en, distil-small.en

```

I guess it's easier to just rename the file.
